-- public.trade_execution_decisions definition

-- Drop table

-- DROP TABLE public.trade_execution_decisions;

CREATE TABLE public.trade_execution_decisions (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	correlationid varchar(40) NOT NULL,
	decisionid varchar(40) NULL,
	idempotencykey varchar(64) NULL,
	strategyname varchar(120) NULL,
	symbol int4 NULL,
	"action" int4 NULL,
	rawsignal int4 NULL,
	tradingmode int4 NULL,
	executionintent int4 NULL,
	confidence numeric NULL,
	minconfidence numeric NULL,
	reason text NULL,
	decisionstatus int4 NULL,
	guardstage int4 NULL,
	isincooldown bool DEFAULT false NULL,
	cooldownremainingseconds int8 NULL,
	cooldownlasttrade timestamptz NULL,
	idempotencyduplicate bool DEFAULT false NULL,
	riskisallowed bool NULL,
	riskreason text NULL,
	stoplossprice numeric NULL,
	takeprofitprice numeric NULL,
	executionsuccess bool DEFAULT false NULL,
	localorderid int8 NULL,
	exchangeorderid int8 NULL,
	executionerror text NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz NULL,
	side int4 NULL,
	CONSTRAINT trade_execution_decisions_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX idx_trade_exec_decisionid ON public.trade_execution_decisions USING btree (decisionid) WHERE (decisionid IS NOT NULL);