CREATE TABLE IF NOT EXISTS trade_execution_decisions
(
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correlationid           varchar(40)  NOT NULL,
    decisionid              varchar(40),
    strategyname            varchar(120),
    symbol                  integer,
    action                  integer,
    rawsignal               integer,
    tradingmode             integer,
    executionintent         integer,
    side                    integer,
    decisionstatus          integer,
    guardstage              integer,
    reason                  text,
    riskisallowed           boolean,
    stoplossprice           numeric,
    takeprofitprice         numeric,
    expectedmovepercent     numeric,
    trendconfidencescore    integer,
    shortmaslopepercent     numeric,
    trendstrengthpercent    numeric,
    executionsuccess        boolean DEFAULT false,
    localorderid            bigint,
    exchangeorderid         bigint,
    executionerror          text,
    created_at              timestamptz DEFAULT now(),
    updated_at              timestamptz
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_trade_exec_decisionid
    ON trade_execution_decisions (decisionid)
    WHERE decisionid IS NOT NULL;
