using System.Text.Json;
using TradingBot.Domain.Enums;

namespace TradingBot.Backtest;

/// <summary>
/// NoPaidDataShortWindowFlowResearchV1CrossSymbol — research/backtest only, free data only.
/// Generalizes the V1 short-window flow activation research to BTC/ETH/BNB/SOL across 5m/15m/30m,
/// long+short, and a fixed trade geometry grid. The frozen BNB incubation candidate, its state
/// file, and its history are never read, modified, or regenerated by this branch.
/// No live trading, no real orders, no production changes.
/// </summary>
public sealed class NoPaidDataShortWindowFlowResearchV1CrossSymbolApplication(BacktestSettings settings)
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };

    private sealed record TradeStats(
        int Count, decimal Net, decimal WinRate, decimal ProfitFactor, decimal MaxDrawdown, int MaxConsecutiveLosses);

    public async Task<NoPaidDataShortWindowFlowResearchV1CrossSymbolRunResult> RunAsync(CancellationToken cancellationToken)
    {
        var runAtUtc = DateTime.UtcNow;
        var loader = new HistoricalKlineDataLoader(settings);
        var downloadOutcomes = new List<ShortWindowDownloadOutcome>();

        if (settings.BootstrapFuturesData)
        {
            await RefreshCandlesAsync(loader, cancellationToken);
            var flowDownloader = new ShortWindowFlowDataDownloader();
            downloadOutcomes.AddRange(await flowDownloader.DownloadAllAsync(
                settings.DataDirectory, FuturesMarketDataCatalog.Symbols, runAtUtc.AddDays(-365), runAtUtc, cancellationToken));
        }

        var validated = new Dictionary<TradingSymbol, SymbolValidationResult>();
        foreach (var symbol in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols)
        {
            var symbolData = await loader.LoadAndValidateAsync(symbol, cancellationToken);
            if (symbolData.Candles.Count == 0)
                throw new InvalidOperationException($"{symbol} local 1m data required for cross-symbol research.");
            validated[symbol] = symbolData;
        }

        var (dataStartUtc, dataEndUtc) = RobustnessWindowResolver.ResolveDataBounds(validated);
        var spanDays = (int)Math.Max(1, (dataEndUtc - dataStartUtc).TotalDays);
        var windowStart = dataEndUtc.AddDays(-Math.Min(365, spanDays));
        if (windowStart < dataStartUtc)
            windowStart = dataStartUtc;

        var windowed1m = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols.ToDictionary(
            s => s,
            s => CandleWindowSlicer.Slice(validated[s].Candles, windowStart, dataEndUtc));

        var btcContext = new BtcContextIndex(windowed1m[TradingSymbol.BTCUSDT]);
        var marketWideContext = new MarketWideContextIndex(
            windowed1m.ToDictionary(kv => kv.Key, kv => (IReadOnlyList<KlineCandle>)kv.Value),
            includeBtcInProxy: true);

        var intervalCandles = new Dictionary<(TradingSymbol, string), IReadOnlyList<KlineCandle>>();
        foreach (var symbol in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols)
        foreach (var interval in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Intervals)
        {
            intervalCandles[(symbol, interval)] = CandleAggregator
                .Aggregate(symbol, windowed1m[symbol], "1m", interval).Candles;
        }

        var futuresLoader = new FuturesMarketDataLoader(settings.DataDirectory);
        var flowIndexes = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols.ToDictionary(
            s => s,
            s => new ShortWindowFlowFeatureIndex(
                futuresLoader, s, intervalCandles[(s, "5m")], windowed1m[TradingSymbol.BTCUSDT]));

        var flowStarts = flowIndexes.Values
            .Select(f => f.FlowCoverageStartUtc)
            .Where(t => t.HasValue)
            .Select(t => t!.Value)
            .ToArray();
        var studyEnd = dataEndUtc;
        var studyStart = flowStarts.Length > 0 ? flowStarts.Max() : studyEnd.AddDays(-30);
        if (studyStart < windowStart)
            studyStart = windowStart;
        if (studyStart >= studyEnd)
            studyStart = studyEnd.AddDays(-1);
        var studyMid = studyStart + TimeSpan.FromTicks((studyEnd - studyStart).Ticks / 2);

        var coverage = NoPaidDataShortWindowMultiSymbolResearchV2Application.BuildCoverage(
            futuresLoader, validated, studyStart, studyEnd);

        // Base trade streams: 4 symbols x 3 intervals x 2 directions x 5 geometries.
        var scans = new List<NoPaidDataShortWindowFlowResearchV1CrossSymbolSimulator.GeometryScan>();
        foreach (var symbol in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols)
        foreach (var interval in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Intervals)
        {
            cancellationToken.ThrowIfCancellationRequested();
            scans.AddRange(NoPaidDataShortWindowFlowResearchV1CrossSymbolSimulator.ScanSymbolInterval(
                symbol, interval, intervalCandles[(symbol, interval)], windowed1m[symbol],
                flowIndexes[symbol], btcContext, marketWideContext, studyStart, studyEnd, cancellationToken));
        }

        var activationConfigs = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.BuildActivationConfigs();

        var summaryRows = new List<CrossSymbolSummaryRow>();
        var leaderboard = new List<CrossSymbolLeaderboardRow>();
        var tradeRows = new List<CrossSymbolTradeRow>();
        var periodRows = new List<CrossSymbolPeriodRow>();
        var costRows = new List<CrossSymbolCostSensitivityRow>();

        foreach (var scan in scans)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var key = scan.Key;
            var flowIndex = flowIndexes[key.Symbol];
            var moderateTrades = NoPaidDataShortWindowFlowResearchV1Aggregator.MapCostScenario(
                scan.BaseTrades, NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.PrimaryCostScenario, btcContext, dataEndUtc);

            // Evaluate the full activation grid (no period collection) and pick the best by net.
            CrossSymbolSimOutcome? baseline = null;
            CrossSymbolSimOutcome? best = null;
            var netPositiveConfigs = 0;
            foreach (var config in activationConfigs)
            {
                var sim = NoPaidDataShortWindowFlowResearchV1CrossSymbolEngine.Simulate(
                    key, config, moderateTrades, studyStart, studyEnd, flowIndex,
                    NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.PrimaryCostScenario, collectPeriods: false);
                var net = sim.TakenTrades.Sum(t => t.NetPnlQuote);
                if (config.IsAlwaysOn)
                {
                    baseline = sim;
                    continue;
                }

                if (net > 0m && sim.TakenTrades.Count > 0)
                    netPositiveConfigs++;
                if (sim.TakenTrades.Count > 0
                    && (best is null || net > best.TakenTrades.Sum(t => t.NetPnlQuote)))
                {
                    best = sim;
                }
            }

            var chosenConfig = best?.Config ?? baseline!.Config;

            // Re-run the chosen rule with full period detail (futures-moderate).
            var chosen = NoPaidDataShortWindowFlowResearchV1CrossSymbolEngine.Simulate(
                key, chosenConfig, moderateTrades, studyStart, studyEnd, flowIndex,
                NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.PrimaryCostScenario, collectPeriods: true);
            periodRows.AddRange(chosen.Periods);

            var chosenStats = Stats(chosen.TakenTrades);
            var baselineStats = Stats(baseline!.TakenTrades);

            // Cost scenarios for the chosen rule.
            var netByScenario = new Dictionary<string, decimal>(StringComparer.OrdinalIgnoreCase);
            foreach (var scenario in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.CostScenarios)
            {
                var scenarioTrades = NoPaidDataShortWindowFlowResearchV1Aggregator.MapCostScenario(
                    scan.BaseTrades, scenario, btcContext, dataEndUtc);
                var scenarioSim = NoPaidDataShortWindowFlowResearchV1CrossSymbolEngine.Simulate(
                    key, chosenConfig, scenarioTrades, studyStart, studyEnd, flowIndex, scenario, collectPeriods: false);
                var scenarioStats = Stats(scenarioSim.TakenTrades);
                netByScenario[scenario] = scenarioStats.Net;
                costRows.Add(new CrossSymbolCostSensitivityRow
                {
                    Symbol = key.Symbol.ToString(),
                    Interval = key.Interval,
                    Direction = key.Direction.ToString(),
                    TargetPercent = key.TargetPercent,
                    StopPercent = key.StopPercent,
                    ActivationRule = chosenConfig.ActivationRuleName,
                    CostScenario = scenario,
                    TradeCount = scenarioStats.Count,
                    NetPnlQuote = scenarioStats.Net,
                    WinRate = scenarioStats.WinRate,
                    ProfitFactor = scenarioStats.ProfitFactor,
                    NetPositive = scenarioStats.Net > 0m
                });
            }

            foreach (var t in chosen.TakenTrades)
            {
                tradeRows.Add(new CrossSymbolTradeRow
                {
                    Symbol = key.Symbol.ToString(),
                    Interval = key.Interval,
                    Direction = key.Direction.ToString(),
                    TargetPercent = key.TargetPercent,
                    StopPercent = key.StopPercent,
                    ActivationRule = chosenConfig.ActivationRuleName,
                    EntryTimeUtc = t.EntryTimeUtc,
                    ExitTimeUtc = t.ExitTimeUtc,
                    NetPnlQuote = Math.Round(t.NetPnlQuote, 8),
                    IsWinner = t.NetPnlQuote > 0m,
                    ExitReason = t.ExitReason,
                    CostScenario = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.PrimaryCostScenario
                });
            }

            summaryRows.Add(new CrossSymbolSummaryRow
            {
                Symbol = key.Symbol.ToString(),
                Interval = key.Interval,
                Direction = key.Direction.ToString(),
                TargetPercent = key.TargetPercent,
                StopPercent = key.StopPercent,
                HoldHours = key.MaxHoldMinutes / 60,
                SignalCount = scan.SignalCount,
                BaselineTrades = baselineStats.Count,
                BaselineNet = baselineStats.Net,
                BaselineWinRate = baselineStats.WinRate,
                BaselineProfitFactor = baselineStats.ProfitFactor,
                BestActivationRule = chosenConfig.ActivationRuleName,
                BestActivationNet = chosenStats.Net,
                BestActivationTrades = chosenStats.Count,
                ConfigsEvaluated = activationConfigs.Count,
                ConfigsNetPositive = netPositiveConfigs,
                CostScenario = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.PrimaryCostScenario
            });

            leaderboard.Add(BuildLeaderboardRow(key, chosen, chosenStats, netByScenario, studyMid));
        }

        var orderedLeaderboard = leaderboard
            .OrderByDescending(r => r.Recommendation == "FreezeForForwardIncubation")
            .ThenByDescending(r => r.Recommendation == "Watchlist")
            .ThenByDescending(r => r.NetPnl)
            .ToArray();

        var answers = BuildAnswers(orderedLeaderboard, summaryRows, studyStart, studyEnd);

        var result = new NoPaidDataShortWindowFlowResearchV1CrossSymbolRunResult(
            coverage, summaryRows, orderedLeaderboard, tradeRows, periodRows, costRows, answers, studyStart, studyEnd);

        Directory.CreateDirectory(settings.OutputDirectory);
        var writer = new NoPaidDataShortWindowFlowResearchV1CrossSymbolReportWriter(settings.OutputDirectory);
        await writer.WriteAsync(result, cancellationToken);

        await File.WriteAllTextAsync(
            Path.Combine(settings.OutputDirectory, "run-metadata.json"),
            JsonSerializer.Serialize(new
            {
                mode = "no-paid-short-window-v1-cross-symbol",
                settings.DataDirectory,
                settings.OutputDirectory,
                runAtUtc,
                studyStartUtc = studyStart,
                studyEndUtc = studyEnd,
                symbols = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols.Select(s => s.ToString()),
                intervals = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Intervals,
                geometryGrid = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.GeometryGrid
                    .Select(g => new { target = g.Target, stop = g.Stop, holdMinutes = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.HoldMinutes }),
                comboCount = scans.Count,
                activationConfigCount = activationConfigs.Count,
                baseEntryFamily = "NearHighElevatedVol (short) / NearLowElevatedVol (long) — Rule01-style family, fixed thresholds",
                bootstrapAttempted = settings.BootstrapFuturesData,
                downloadOutcomes = downloadOutcomes.Select(o => new { o.Symbol, o.SourceKey, o.Success, o.AddedCount, o.TotalCount, o.Message }),
                frozenIncubationTrackTouched = false,
                frozenProfileProtected = "Frozen_BNB_Rule01Short_FundingNormal_Daily24h_V1 (not read, not modified, not regenerated)",
                backtestOnly = true,
                liveFuturesRecommended = false,
                paidDataUsed = false,
                realOrdersPlaced = false
            }, JsonOptions),
            cancellationToken);

        return result;
    }

    private static CrossSymbolLeaderboardRow BuildLeaderboardRow(
        CrossSymbolComboKey key,
        CrossSymbolSimOutcome chosen,
        TradeStats stats,
        IReadOnlyDictionary<string, decimal> netByScenario,
        DateTime studyMid)
    {
        var latencyNet = netByScenario.GetValueOrDefault(NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.ModerateLatencyScenario);
        var stressPlusNet = netByScenario.GetValueOrDefault(NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.StressPlusScenario);
        var positivePeriodRate = chosen.ActivatedPeriodCount > 0
            ? Math.Round((decimal)chosen.PositivePeriodCount / chosen.ActivatedPeriodCount, 6)
            : 0m;

        var dailyNets = chosen.TakenTrades.GroupBy(t => t.ExitTimeUtc.Date).Select(g => g.Sum(t => t.NetPnlQuote)).ToArray();
        var dayShareOk = stats.Net > 0m && dailyNets.Length > 0
                         && dailyNets.Max() / stats.Net <= NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MaxSingleDayProfitShare;

        // Split-half consistency: the rule was selected as best-of-grid on this single window,
        // so flag it unless both halves of the window are independently positive.
        var firstHalfNet = chosen.TakenTrades.Where(t => t.EntryTimeUtc < studyMid).Sum(t => t.NetPnlQuote);
        var secondHalfNet = chosen.TakenTrades.Where(t => t.EntryTimeUtc >= studyMid).Sum(t => t.NetPnlQuote);
        var overfitWarning = !(firstHalfNet > 0m && secondHalfNet > 0m);

        var criteria = new[]
        {
            stats.Count >= NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MinTradeCount,
            stats.Net > 0m,
            latencyNet > 0m,
            stressPlusNet >= NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.StressPlusCollapseFloorQuote,
            positivePeriodRate >= NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MinPositivePeriodRate,
            stats.MaxConsecutiveLosses <= NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MaxConsecutiveLossesLimit,
            dayShareOk,
            chosen.ClusterCount >= 2
        };
        var allPass = criteria.All(c => c);

        var sparseWarning = stats.Count < NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MinTradeCount
                            || (!chosen.Config.IsAlwaysOn && chosen.ActivatedPeriodCount < NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.MinActivatedPeriodsForConfidence);
        var singleClusterWarning = chosen.ClusterCount <= 1;

        var recommendation = NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.ResolveRecommendation(
            allPass, overfitWarning, stats.Count, stats.Net, latencyNet);

        return new CrossSymbolLeaderboardRow
        {
            Symbol = key.Symbol.ToString(),
            Interval = key.Interval,
            Direction = key.Direction.ToString(),
            TargetPercent = key.TargetPercent,
            StopPercent = key.StopPercent,
            HoldHours = key.MaxHoldMinutes / 60,
            ActivationRule = chosen.Config.ActivationRuleName,
            TradeCount = stats.Count,
            NetPnl = stats.Net,
            WinRate = stats.WinRate,
            ProfitFactor = stats.ProfitFactor,
            MaxDrawdown = stats.MaxDrawdown,
            MaxConsecutiveLosses = stats.MaxConsecutiveLosses,
            PositiveActivatedPeriodsPercent = Math.Round(positivePeriodRate * 100m, 2),
            ModerateLatencyNet = latencyNet,
            StressPlusNet = stressPlusNet,
            SparseWarning = sparseWarning,
            OverfitWarning = overfitWarning,
            SingleClusterWarning = singleClusterWarning,
            Recommendation = recommendation,
            SuggestedFrozenProfileName = recommendation == "FreezeForForwardIncubation"
                ? NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.SuggestFrozenProfileName(key, chosen.Config.ActivationRuleName)
                : string.Empty,
            Notes = "Best activation rule selected by net on this single ~30d window; OverfitWarning is set unless both window halves are independently positive. Research only — no live trading recommendation."
        };
    }

    private static TradeStats Stats(IReadOnlyList<RegimeDriftDiagnosticTrade> trades)
    {
        if (trades.Count == 0)
            return new TradeStats(0, 0m, 0m, 0m, 0m, 0);

        var ordered = trades.OrderBy(t => t.ExitTimeUtc).ToArray();
        var net = ordered.Sum(t => t.NetPnlQuote);
        var wins = ordered.Count(t => t.NetPnlQuote > 0m);
        var grossWin = ordered.Where(t => t.NetPnlQuote > 0m).Sum(t => t.NetPnlQuote);
        var grossLoss = Math.Abs(ordered.Where(t => t.NetPnlQuote <= 0m).Sum(t => t.NetPnlQuote));
        var pf = grossLoss == 0m ? (grossWin > 0m ? 999m : 0m) : Math.Round(grossWin / grossLoss, 6);

        decimal equity = 0m, peak = 0m, maxDd = 0m;
        int consec = 0, maxConsec = 0;
        foreach (var t in ordered)
        {
            equity += t.NetPnlQuote;
            if (equity > peak) peak = equity;
            var dd = peak - equity;
            if (dd > maxDd) maxDd = dd;
            if (t.NetPnlQuote <= 0m)
            {
                consec++;
                if (consec > maxConsec) maxConsec = consec;
            }
            else
            {
                consec = 0;
            }
        }

        return new TradeStats(
            ordered.Length,
            Math.Round(net, 8),
            Math.Round((decimal)wins / ordered.Length, 6),
            pf,
            Math.Round(maxDd, 8),
            maxConsec);
    }

    private static IReadOnlyList<ReachabilityResearchAnswer> BuildAnswers(
        IReadOnlyList<CrossSymbolLeaderboardRow> leaderboard,
        IReadOnlyList<CrossSymbolSummaryRow> summary,
        DateTime studyStart,
        DateTime studyEnd)
    {
        var freeze = leaderboard.Where(r => r.Recommendation == "FreezeForForwardIncubation").ToArray();
        var watchlist = leaderboard.Where(r => r.Recommendation == "Watchlist").ToArray();
        var needsData = leaderboard.Count(r => r.Recommendation == "NeedsMoreData");
        var failed = leaderboard.Count(r => r.Recommendation == "CandidateFailed");
        var parked = leaderboard.Count(r => r.Recommendation == "Park");
        var bySymbol = leaderboard
            .GroupBy(r => r.Symbol)
            .Select(g => $"{g.Key}: best net {g.Max(r => r.NetPnl):F2}")
            .ToArray();
        var positiveBaselines = summary.Count(s => s.BaselineNet > 0m);

        return
        [
            new ReachabilityResearchAnswer
            {
                Question = "Does the V1-style short-window flow activation generalize across symbols?",
                Answer = $"Study window {studyStart:yyyy-MM-dd} -> {studyEnd:yyyy-MM-dd}. Of {summary.Count} symbol/interval/direction/geometry combos, {positiveBaselines} have a positive always-on baseline under futures-moderate. Per symbol best chosen-rule nets: {string.Join("; ", bySymbol)}.",
                Verdict = positiveBaselines > summary.Count / 2 ? "BroadlyPositiveWindow" : "MixedAcrossSymbols"
            },
            new ReachabilityResearchAnswer
            {
                Question = "Did any candidate pass all success criteria?",
                Answer = freeze.Length > 0
                    ? $"Yes: {string.Join("; ", freeze.Select(r => $"{r.Symbol} {r.Interval} {r.Direction} T{r.TargetPercent:0.00}/S{r.StopPercent:0.00} + {r.ActivationRule} (net {r.NetPnl:F2})"))}. Proposals only — the frozen BNB incubation candidate is not replaced."
                    : $"No candidate passed every criterion without an overfit warning. Watchlist: {watchlist.Length}, NeedsMoreData: {needsData}, Park: {parked}, CandidateFailed: {failed}.",
                Verdict = freeze.Length > 0 ? "FreezeProposalsExist" : "NoFreezeProposals"
            },
            new ReachabilityResearchAnswer
            {
                Question = "How trustworthy are the leaderboard winners?",
                Answer = $"Each leaderboard row picks the best of {NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.BuildActivationConfigs().Count} activation configs on a single ~30d window, so selection bias is high. {leaderboard.Count(r => r.OverfitWarning)} of {leaderboard.Count} rows carry an overfit warning (window halves not independently positive). Treat all results as hypotheses for forward incubation, not validated edges.",
                Verdict = "SelectionBiasHigh"
            },
            new ReachabilityResearchAnswer
            {
                Question = "What should happen next?",
                Answer = freeze.Length > 0
                    ? "Review the freeze proposals, pick at most one per symbol, and validate them in a separate forward-incubation track (the existing frozen BNB track stays untouched). Keep merging free flow data daily."
                    : "Keep merging free flow data and re-run once the window exceeds 35-45 days; the V1-style activation needs more forward data before any freeze decision.",
                Verdict = freeze.Length > 0 ? "ReviewFreezeProposals" : "KeepCollecting",
                Details = new Dictionary<string, object?>
                {
                    ["backtestOnly"] = true,
                    ["liveFuturesRecommended"] = false,
                    ["paidDataUsed"] = false,
                    ["frozenBnbCandidateTouched"] = false
                }
            }
        ];
    }

    private async Task RefreshCandlesAsync(HistoricalKlineDataLoader loader, CancellationToken cancellationToken)
    {
        var downloader = new BinanceKlineBootstrapDownloader();
        foreach (var symbol in NoPaidDataShortWindowFlowResearchV1CrossSymbolCatalog.Symbols)
        {
            var existing = await loader.LoadAndValidateAsync(symbol, cancellationToken);
            var lastUtc = existing.Candles.Count > 0 ? existing.Candles[^1].OpenTimeUtc : DateTime.UtcNow.AddDays(-35);
            var nowUtc = DateTime.UtcNow;
            if ((nowUtc - lastUtc) < TimeSpan.FromMinutes(30))
                continue;
            var path = Path.Combine(settings.DataDirectory, $"{symbol}-1m.json");
            await downloader.DownloadAndMergeToJsonAsync(
                symbol.ToString(), path, 1000, lastUtc.AddHours(-2), nowUtc, cancellationToken);
        }
    }
}
