using TradingBot.Domain.Enums;

namespace TradingBot.Backtest;

/// <summary>
/// NoPaidDataShortWindowMultiSymbolResearchV2 configuration. All entry thresholds, split schemes,
/// activation grids, and success criteria are fixed up-front in this file and are never tuned
/// against validation/holdout results. The frozen V1 BNB incubation track is not referenced,
/// modified, or regenerated by anything in this branch.
/// </summary>
public static class NoPaidDataShortWindowMultiSymbolResearchV2Catalog
{
    public const string PrimaryCostScenario = "futures-moderate";
    public const string ModerateLatencyScenario = "futures-moderate-latency-002";
    public const string StressPlusScenario = "futures-stress-plus";

    public static readonly string[] CostScenarios =
    [
        "futures-moderate",
        "futures-moderate-latency-002",
        "futures-stress",
        "futures-stress-latency-002",
        "futures-stress-plus"
    ];

    public static readonly TradingSymbol[] CoreSymbols =
    [
        TradingSymbol.BTCUSDT,
        TradingSymbol.ETHUSDT,
        TradingSymbol.BNBUSDT,
        TradingSymbol.SOLUSDT
    ];

    /// <summary>Optional symbols are only used when local data is clean; reported either way.</summary>
    public static readonly string[] OptionalSymbolNames =
        ["XRPUSDT", "ADAUSDT", "DOGEUSDT", "AVAXUSDT", "LINKUSDT", "LTCUSDT"];

    public static readonly string[] Intervals = ["5m", "15m", "30m"];

    // Eligibility: need a real candle history and at least two weeks of flow data so that
    // discovery/validation/holdout segments all contain flow-aware signals.
    public const decimal MinCandleSpanDaysForEligibility = 60m;
    public const decimal MinFlowSpanDaysForEligibility = 14m;

    // Entry thresholds (fixed, interpretable).
    public const decimal NearExtremeAtrMultiple = 0.6m;        // distance from swing high/low <= 0.6 x ATR
    public const decimal ReversalNearExtremeAtrMultiple = 1.0m;
    public const decimal FundingNormalZMax = 1.0m;
    public const decimal LongShortStretchZMin = 1.5m;
    public const decimal TrendSlopeMinPercent = 0.02m;
    public const decimal BtcContextMinReturnPercent = 0.10m;
    public const decimal CompressionRangeAtrMultiple = 3.0m;
    public const decimal CompressionOiChangeMinPercent = 0.3m;
    public const decimal TakerImbalanceLongMin = 1.05m;
    public const decimal TakerImbalanceShortMax = 0.95m;
    public const decimal BreakoutClosePositionHigh = 0.7m;
    public const decimal BreakoutClosePositionLow = 0.3m;
    public const decimal VolumeExpansionMin = 1.5m;

    // Activation gate thresholds (fixed).
    public const decimal GateTakerLongMin = 1.02m;
    public const decimal GateTakerShortMax = 0.98m;
    public const int ActivationMinLookbackTrades = 5;

    // Discovery selection thresholds (fixed; applied to discovery segment only).
    public const int DiscoveryMinTrades = 8;
    public const decimal DiscoveryMinProfitFactor = 1.2m;
    public const int MaxActivationCandidates = 12;

    // Success criteria (fixed).
    public const int MinValidationHoldoutTrades = 20;
    public const decimal StressPlusCollapseFloorQuote = -10m;
    public const decimal MaxSingleDayProfitShare = 0.5m;
    public const decimal MinPositivePeriodRate = 0.40m;
    public const int MaxConsecutiveLossesLimit = 5;
    public const int MinActivatedPeriodsForConfidence = 8;

    public const string PrimarySplitScheme = "Split40_20_40";
    public const decimal RollingWeeklyMinSpanDays = 35m;

    public sealed record IntervalGeometry(decimal TargetPercent, decimal StopPercent, int MaxHoldMinutes, int CooldownCandles);

    /// <summary>One fixed trade geometry per interval for every family (no per-family tuning).</summary>
    public static IntervalGeometry GeometryFor(string interval) => interval switch
    {
        "5m" => new IntervalGeometry(1.75m, 1.00m, 240, 6),
        "15m" => new IntervalGeometry(2.25m, 1.25m, 480, 4),
        "30m" => new IntervalGeometry(3.00m, 1.50m, 720, 3),
        _ => throw new ArgumentOutOfRangeException(nameof(interval), interval, "Unsupported interval.")
    };

    public static IReadOnlyList<(MultiSymbolRuleFamily Family, LongShortDirection Direction)> FamilyCombos(TradingSymbol symbol)
    {
        var combos = new List<(MultiSymbolRuleFamily, LongShortDirection)>
        {
            (MultiSymbolRuleFamily.NearHighElevatedVol, LongShortDirection.Short),
            (MultiSymbolRuleFamily.NearLowElevatedVol, LongShortDirection.Long),
            (MultiSymbolRuleFamily.FundingNormalTrendContinuation, LongShortDirection.Long),
            (MultiSymbolRuleFamily.FundingNormalTrendContinuation, LongShortDirection.Short),
            (MultiSymbolRuleFamily.LongShortRatioStretchReversal, LongShortDirection.Long),
            (MultiSymbolRuleFamily.LongShortRatioStretchReversal, LongShortDirection.Short),
            (MultiSymbolRuleFamily.FlowCompressionBreakout, LongShortDirection.Long),
            (MultiSymbolRuleFamily.FlowCompressionBreakout, LongShortDirection.Short)
        };

        // BTC context gating a BTC trade is circular; only alts get this family.
        if (symbol != TradingSymbol.BTCUSDT)
        {
            combos.Add((MultiSymbolRuleFamily.BtcContextDirectional, LongShortDirection.Long));
            combos.Add((MultiSymbolRuleFamily.BtcContextDirectional, LongShortDirection.Short));
        }

        return combos;
    }

    /// <summary>
    /// Entry evaluation. Candle features come from the completed signal candle; the flow snapshot
    /// is taken as-of that candle's close (never later). Families that need flow data simply do
    /// not fire when the data is missing.
    /// </summary>
    public static bool MatchesFamily(
        MultiSymbolRuleFamily family,
        LongShortDirection direction,
        MarketRegimeForwardEdgeScanner.RegimeCandleFeatures f,
        ShortWindowFlowSnapshot s)
    {
        return family switch
        {
            MultiSymbolRuleFamily.NearHighElevatedVol =>
                direction == LongShortDirection.Short
                && f.AtrPercent > 0m
                && f.DistanceFromRecentHighPercent <= NearExtremeAtrMultiple * f.AtrPercent
                && ElevatedVol(f),

            MultiSymbolRuleFamily.NearLowElevatedVol =>
                direction == LongShortDirection.Long
                && f.AtrPercent > 0m
                && f.DistanceFromRecentLowPercent <= NearExtremeAtrMultiple * f.AtrPercent
                && ElevatedVol(f),

            MultiSymbolRuleFamily.FundingNormalTrendContinuation =>
                s.FundingZScore.HasValue
                && Math.Abs(s.FundingZScore.Value) <= FundingNormalZMax
                && f.VolatilityRegime != "Low"
                && (direction == LongShortDirection.Long
                    ? f.TrendSlopePercent > TrendSlopeMinPercent && f.RecentReturn30 > 0m
                    : f.TrendSlopePercent < -TrendSlopeMinPercent && f.RecentReturn30 < 0m),

            MultiSymbolRuleFamily.LongShortRatioStretchReversal =>
                s.GlobalLongShortZScore.HasValue
                && f.AtrPercent > 0m
                && (direction == LongShortDirection.Short
                    ? s.GlobalLongShortZScore.Value >= LongShortStretchZMin
                      && f.DistanceFromRecentHighPercent <= ReversalNearExtremeAtrMultiple * f.AtrPercent
                    : s.GlobalLongShortZScore.Value <= -LongShortStretchZMin
                      && f.DistanceFromRecentLowPercent <= ReversalNearExtremeAtrMultiple * f.AtrPercent),

            MultiSymbolRuleFamily.BtcContextDirectional =>
                f.BtcReturn30mPercent.HasValue && f.BtcReturn60mPercent.HasValue
                && (direction == LongShortDirection.Long
                    ? f.BtcReturn30mPercent.Value > BtcContextMinReturnPercent
                      && f.BtcReturn60mPercent.Value > BtcContextMinReturnPercent
                      && f.TrendSlopePercent > 0m
                    : f.BtcReturn30mPercent.Value < -BtcContextMinReturnPercent
                      && f.BtcReturn60mPercent.Value < -BtcContextMinReturnPercent
                      && f.TrendSlopePercent < 0m),

            MultiSymbolRuleFamily.FlowCompressionBreakout =>
                s.OiChange30mPercent.HasValue && s.TakerBuySellImbalance.HasValue
                && f.AtrPercent > 0m
                && f.RangeWidthPercent <= CompressionRangeAtrMultiple * f.AtrPercent
                && f.VolatilityRegime != "Elevated"
                && s.OiChange30mPercent.Value >= CompressionOiChangeMinPercent
                && (direction == LongShortDirection.Long
                    ? s.TakerBuySellImbalance.Value >= TakerImbalanceLongMin
                      && f.ClosePositionInRange >= BreakoutClosePositionHigh
                    : s.TakerBuySellImbalance.Value <= TakerImbalanceShortMax
                      && f.ClosePositionInRange <= BreakoutClosePositionLow),

            _ => false
        };
    }

    private static bool ElevatedVol(MarketRegimeForwardEdgeScanner.RegimeCandleFeatures f)
        => f.VolatilityRegime == "Elevated"
           || (f.VolatilityRegime == "Normal" && f.VolumeExpansionRatio >= VolumeExpansionMin);

    /// <summary>
    /// Direction-aware activation gate evaluation against an as-of snapshot.
    /// Returns (available, pass); when required data is missing, available=false and pass=false.
    /// </summary>
    public static (bool Available, bool Pass) EvaluateGate(
        MultiSymbolActivationGate gate,
        LongShortDirection direction,
        ShortWindowFlowSnapshot s)
    {
        switch (gate)
        {
            case MultiSymbolActivationGate.None:
                return (true, true);
            case MultiSymbolActivationGate.FundingNormal:
                return s.FundingZScore.HasValue
                    ? (true, Math.Abs(s.FundingZScore.Value) <= FundingNormalZMax)
                    : (false, false);
            case MultiSymbolActivationGate.BtcContext60mAgrees:
                return s.BtcReturn60mPercent.HasValue
                    ? (true, direction == LongShortDirection.Long
                        ? s.BtcReturn60mPercent.Value > 0m
                        : s.BtcReturn60mPercent.Value < 0m)
                    : (false, false);
            case MultiSymbolActivationGate.LongShortStretchedAgainstDirection:
                return s.GlobalLongShortZScore.HasValue
                    ? (true, direction == LongShortDirection.Short
                        ? s.GlobalLongShortZScore.Value >= LongShortStretchZMin
                        : s.GlobalLongShortZScore.Value <= -LongShortStretchZMin)
                    : (false, false);
            case MultiSymbolActivationGate.OiChangeConfirms:
                return s.OiChange30mPercent.HasValue
                    ? (true, s.OiChange30mPercent.Value > 0m)
                    : (false, false);
            case MultiSymbolActivationGate.TakerImbalanceConfirms:
            {
                var imbalance = s.TakerImbalance1h ?? s.TakerBuySellImbalance;
                return imbalance.HasValue
                    ? (true, direction == LongShortDirection.Long
                        ? imbalance.Value >= GateTakerLongMin
                        : imbalance.Value <= GateTakerShortMax)
                    : (false, false);
            }
            case MultiSymbolActivationGate.VolatilityNormal:
                return string.IsNullOrEmpty(s.VolatilityRegime)
                    ? (false, false)
                    : (true, s.VolatilityRegime == "Normal");
            case MultiSymbolActivationGate.VolatilityElevated:
                return string.IsNullOrEmpty(s.VolatilityRegime)
                    ? (false, false)
                    : (true, s.VolatilityRegime == "Elevated");
            case MultiSymbolActivationGate.RecentNetPositive:
                return (true, true); // performance gate handled by the engine from completed trades
            default:
                return (false, false);
        }
    }

    public static IReadOnlyList<MultiSymbolActivationConfig> BuildActivationConfigs()
    {
        int[] checkpoints = [4, 24];
        int[] activationPeriods = [4, 12, 24, 72];
        int[] lookbacks = [3, 7, 14];
        MultiSymbolActivationGate[] flowGates =
        [
            MultiSymbolActivationGate.FundingNormal,
            MultiSymbolActivationGate.BtcContext60mAgrees,
            MultiSymbolActivationGate.LongShortStretchedAgainstDirection,
            MultiSymbolActivationGate.OiChangeConfirms,
            MultiSymbolActivationGate.TakerImbalanceConfirms,
            MultiSymbolActivationGate.VolatilityNormal,
            MultiSymbolActivationGate.VolatilityElevated
        ];

        var configs = new List<MultiSymbolActivationConfig>
        {
            new("AlwaysOn", MultiSymbolActivationGate.None, true, 24, 24, 0, 0)
        };

        foreach (var gate in flowGates)
        foreach (var chk in checkpoints)
        foreach (var act in activationPeriods)
        {
            configs.Add(new MultiSymbolActivationConfig(
                $"Gate_{gate}_Chk{chk}h_Act{act}h", gate, false, chk, act, 3, 0));
        }

        foreach (var chk in checkpoints)
        foreach (var act in activationPeriods)
        foreach (var lb in lookbacks)
        {
            configs.Add(new MultiSymbolActivationConfig(
                $"Perf_RecentNetPositive_Chk{chk}h_Act{act}h_LB{lb}d",
                MultiSymbolActivationGate.RecentNetPositive, false, chk, act, lb, ActivationMinLookbackTrades));
        }

        return configs;
    }

    public static IReadOnlyList<(string Scheme, decimal DiscoveryFraction, decimal ValidationFraction)> SplitSchemes()
        =>
        [
            ("Split40_20_40", 0.40m, 0.20m),
            ("Split50_25_25", 0.50m, 0.25m)
        ];

    public static string SuggestFrozenProfileName(MultiSymbolComboKey key, string activationRule)
    {
        var symbolShort = key.Symbol.ToString().Replace("USDT", "", StringComparison.Ordinal);
        var activationTag = activationRule
            .Replace("Gate_", "", StringComparison.Ordinal)
            .Replace("Perf_", "", StringComparison.Ordinal)
            .Replace("_", "", StringComparison.Ordinal);
        return $"Frozen_{symbolShort}_{key.Family}{key.Direction}_{key.Interval}_{activationTag}_V2Proposal";
    }

    /// <summary>
    /// Candidates explicitly tracked on the watchlist regardless of the generic inclusion rule.
    /// Tracking only — no thresholds were changed and no new search was run for these.
    /// </summary>
    public static readonly (string Symbol, string Interval, string Direction, string RuleFamily)[] TrackedWatchlistCandidates =
    [
        ("SOLUSDT", "30m", "Short", nameof(MultiSymbolRuleFamily.NearHighElevatedVol))
    ];

    public const string NextRerunConditionText =
        "Re-run after the merged flow cache exceeds 35 days so rolling weekly splits activate; if still positive, re-check at 45 and 60 days of merged data.";

    /// <summary>Watchlist recommendation: positive-but-sparse, mixed signs, or holdout collapse.</summary>
    public static string ResolveWatchlistRecommendation(
        decimal validationNet, decimal holdoutNet, int validationHoldoutTrades)
    {
        if (holdoutNet <= -Math.Abs(StressPlusCollapseFloorQuote))
            return "CandidateFailed";
        if (validationNet > 0m && holdoutNet > 0m)
            return validationHoldoutTrades < MinValidationHoldoutTrades ? "NeedsMoreData" : "Watchlist";
        if (validationNet <= 0m && holdoutNet <= 0m)
            return "CandidateFailed";
        return "Park";
    }

    public static string ResolveRecommendation(
        bool allCriteriaPass,
        decimal validationNet,
        decimal holdoutNet,
        int validationHoldoutTrades)
    {
        if (allCriteriaPass)
            return "FreezeForForwardIncubation";
        if (validationNet > 0m && holdoutNet > 0m)
            return validationHoldoutTrades < MinValidationHoldoutTrades ? "NeedsMoreData" : "Watchlist";
        if (validationNet <= 0m && holdoutNet <= 0m)
            return "CandidateFailed";
        return "Park";
    }
}
