<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Configuration\Configuration.cs" />
    <Compile Include="SpotFuturesCrossMarket\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TradingBot.Percistance\TradingBot.Percistance.csproj" />
  </ItemGroup>

</Project>
